apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  selector:
    app: pod-portal-noticias
  ports:
  - port: 80
    #targetPort: <Target Port> Porta que ele despacha, se omitida ele faz o espelhamento
    nodePort: 30000 #RANGE DE 30000 Á 32000
